#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
#
Name     : SPIRV-Tools
Version  : 2023.2
Release  : 12
URL      : https://github.com/KhronosGroup/SPIRV-Tools/archive/v2023.2/SPIRV-Tools-2023.2.tar.gz
Source0  : https://github.com/KhronosGroup/SPIRV-Tools/archive/v2023.2/SPIRV-Tools-2023.2.tar.gz
Source1  : https://github.com/KhronosGroup/SPIRV-Headers/archive/refs/tags/sdk-1.3.243.0.tar.gz
Summary  : Tools for SPIR-V
Group    : Development/Tools
License  : Apache-2.0 MIT
Requires: SPIRV-Tools-bin = %{version}-%{release}
Requires: SPIRV-Tools-lib = %{version}-%{release}
Requires: SPIRV-Tools-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : llvm-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# SPIR-V Tools
NEWS 2023-01-11: Development occurs on the `main` branch.
## Overview

%package bin
Summary: bin components for the SPIRV-Tools package.
Group: Binaries
Requires: SPIRV-Tools-license = %{version}-%{release}

%description bin
bin components for the SPIRV-Tools package.


%package dev
Summary: dev components for the SPIRV-Tools package.
Group: Development
Requires: SPIRV-Tools-lib = %{version}-%{release}
Requires: SPIRV-Tools-bin = %{version}-%{release}
Provides: SPIRV-Tools-devel = %{version}-%{release}
Requires: SPIRV-Tools = %{version}-%{release}

%description dev
dev components for the SPIRV-Tools package.


%package dev32
Summary: dev32 components for the SPIRV-Tools package.
Group: Default
Requires: SPIRV-Tools-lib32 = %{version}-%{release}
Requires: SPIRV-Tools-bin = %{version}-%{release}
Requires: SPIRV-Tools-dev = %{version}-%{release}

%description dev32
dev32 components for the SPIRV-Tools package.


%package lib
Summary: lib components for the SPIRV-Tools package.
Group: Libraries
Requires: SPIRV-Tools-license = %{version}-%{release}

%description lib
lib components for the SPIRV-Tools package.


%package lib32
Summary: lib32 components for the SPIRV-Tools package.
Group: Default
Requires: SPIRV-Tools-license = %{version}-%{release}

%description lib32
lib32 components for the SPIRV-Tools package.


%package license
Summary: license components for the SPIRV-Tools package.
Group: Default

%description license
license components for the SPIRV-Tools package.


%prep
%setup -q -n SPIRV-Tools-2023.2
cd %{_builddir}
tar xf %{_sourcedir}/sdk-1.3.243.0.tar.gz
cd %{_builddir}/SPIRV-Tools-2023.2
mkdir -p external/spirv-headers
cp -r %{_builddir}/SPIRV-Headers-sdk-1.3.243.0/* %{_builddir}/SPIRV-Tools-2023.2/external/spirv-headers

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1687995480
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
%cmake .. -DSPIRV_HEADER_INCLUDE_DIR=/usr/include \
-DSPIRV_TOOLS_BUILD_STATIC=OFF
make  %{?_smp_mflags}
popd
mkdir -p clr-build32
pushd clr-build32
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig:/usr/share/pkgconfig"
export ASFLAGS="${ASFLAGS}${ASFLAGS:+ }--32"
export CFLAGS="${CFLAGS}${CFLAGS:+ }-m32 -mstackrealign"
export CXXFLAGS="${CXXFLAGS}${CXXFLAGS:+ }-m32 -mstackrealign"
export LDFLAGS="${LDFLAGS}${LDFLAGS:+ }-m32 -mstackrealign"
%cmake -DLIB_INSTALL_DIR:PATH=/usr/lib32 -DCMAKE_INSTALL_LIBDIR=/usr/lib32 -DLIB_SUFFIX=32 .. -DSPIRV_HEADER_INCLUDE_DIR=/usr/include \
-DSPIRV_TOOLS_BUILD_STATIC=OFF
make  %{?_smp_mflags}
unset PKG_CONFIG_PATH
popd

%install
export SOURCE_DATE_EPOCH=1687995480
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/SPIRV-Tools
cp %{_builddir}/SPIRV-Headers-sdk-1.3.243.0/LICENSE %{buildroot}/usr/share/package-licenses/SPIRV-Tools/9a84200f47e09abfbde1a6b25028460451b23d03 || :
cp %{_builddir}/SPIRV-Tools-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/SPIRV-Tools/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/SPIRV-Tools-%{version}/utils/vscode/src/lsp/LICENSE %{buildroot}/usr/share/package-licenses/SPIRV-Tools/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
pushd clr-build32
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
if [ -d %{buildroot}/usr/share/pkgconfig ]
then
pushd %{buildroot}/usr/share/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
pushd clr-build
%make_install
popd
## install_append content
ln -s SPIRV-Tools.pc %{buildroot}/usr/lib64/pkgconfig/spirv-tools.pc
ln -s SPIRV-Tools-shared.pc %{buildroot}/usr/lib64/pkgconfig/spirv-tools-shared.pc

## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/spirv-as
/usr/bin/spirv-cfg
/usr/bin/spirv-dis
/usr/bin/spirv-lesspipe.sh
/usr/bin/spirv-link
/usr/bin/spirv-lint
/usr/bin/spirv-opt
/usr/bin/spirv-reduce
/usr/bin/spirv-val

%files dev
%defattr(-,root,root,-)
/usr/include/spirv-tools/instrument.hpp
/usr/include/spirv-tools/libspirv.h
/usr/include/spirv-tools/libspirv.hpp
/usr/include/spirv-tools/linker.hpp
/usr/include/spirv-tools/optimizer.hpp
/usr/lib64/cmake/SPIRV-Tools-diff/SPIRV-Tools-diffConfig.cmake
/usr/lib64/cmake/SPIRV-Tools-diff/SPIRV-Tools-diffTargets-relwithdebinfo.cmake
/usr/lib64/cmake/SPIRV-Tools-diff/SPIRV-Tools-diffTargets.cmake
/usr/lib64/cmake/SPIRV-Tools-link/SPIRV-Tools-linkConfig.cmake
/usr/lib64/cmake/SPIRV-Tools-link/SPIRV-Tools-linkTargets-relwithdebinfo.cmake
/usr/lib64/cmake/SPIRV-Tools-link/SPIRV-Tools-linkTargets.cmake
/usr/lib64/cmake/SPIRV-Tools-lint/SPIRV-Tools-lintConfig.cmake
/usr/lib64/cmake/SPIRV-Tools-lint/SPIRV-Tools-lintTargets-relwithdebinfo.cmake
/usr/lib64/cmake/SPIRV-Tools-lint/SPIRV-Tools-lintTargets.cmake
/usr/lib64/cmake/SPIRV-Tools-opt/SPIRV-Tools-optConfig.cmake
/usr/lib64/cmake/SPIRV-Tools-opt/SPIRV-Tools-optTargets-relwithdebinfo.cmake
/usr/lib64/cmake/SPIRV-Tools-opt/SPIRV-Tools-optTargets.cmake
/usr/lib64/cmake/SPIRV-Tools-reduce/SPIRV-Tools-reduceConfig.cmake
/usr/lib64/cmake/SPIRV-Tools-reduce/SPIRV-Tools-reduceTarget-relwithdebinfo.cmake
/usr/lib64/cmake/SPIRV-Tools-reduce/SPIRV-Tools-reduceTarget.cmake
/usr/lib64/cmake/SPIRV-Tools-tools/SPIRV-Tools-toolsConfig.cmake
/usr/lib64/cmake/SPIRV-Tools-tools/SPIRV-Tools-toolsTargets-relwithdebinfo.cmake
/usr/lib64/cmake/SPIRV-Tools-tools/SPIRV-Tools-toolsTargets.cmake
/usr/lib64/cmake/SPIRV-Tools/SPIRV-ToolsConfig.cmake
/usr/lib64/cmake/SPIRV-Tools/SPIRV-ToolsTarget-relwithdebinfo.cmake
/usr/lib64/cmake/SPIRV-Tools/SPIRV-ToolsTarget.cmake
/usr/lib64/pkgconfig/SPIRV-Tools-shared.pc
/usr/lib64/pkgconfig/SPIRV-Tools.pc
/usr/lib64/pkgconfig/spirv-tools-shared.pc
/usr/lib64/pkgconfig/spirv-tools.pc

%files dev32
%defattr(-,root,root,-)
/usr/lib32/cmake/SPIRV-Tools-diff/SPIRV-Tools-diffConfig.cmake
/usr/lib32/cmake/SPIRV-Tools-diff/SPIRV-Tools-diffTargets-relwithdebinfo.cmake
/usr/lib32/cmake/SPIRV-Tools-diff/SPIRV-Tools-diffTargets.cmake
/usr/lib32/cmake/SPIRV-Tools-link/SPIRV-Tools-linkConfig.cmake
/usr/lib32/cmake/SPIRV-Tools-link/SPIRV-Tools-linkTargets-relwithdebinfo.cmake
/usr/lib32/cmake/SPIRV-Tools-link/SPIRV-Tools-linkTargets.cmake
/usr/lib32/cmake/SPIRV-Tools-lint/SPIRV-Tools-lintConfig.cmake
/usr/lib32/cmake/SPIRV-Tools-lint/SPIRV-Tools-lintTargets-relwithdebinfo.cmake
/usr/lib32/cmake/SPIRV-Tools-lint/SPIRV-Tools-lintTargets.cmake
/usr/lib32/cmake/SPIRV-Tools-opt/SPIRV-Tools-optConfig.cmake
/usr/lib32/cmake/SPIRV-Tools-opt/SPIRV-Tools-optTargets-relwithdebinfo.cmake
/usr/lib32/cmake/SPIRV-Tools-opt/SPIRV-Tools-optTargets.cmake
/usr/lib32/cmake/SPIRV-Tools-reduce/SPIRV-Tools-reduceConfig.cmake
/usr/lib32/cmake/SPIRV-Tools-reduce/SPIRV-Tools-reduceTarget-relwithdebinfo.cmake
/usr/lib32/cmake/SPIRV-Tools-reduce/SPIRV-Tools-reduceTarget.cmake
/usr/lib32/cmake/SPIRV-Tools-tools/SPIRV-Tools-toolsConfig.cmake
/usr/lib32/cmake/SPIRV-Tools-tools/SPIRV-Tools-toolsTargets-relwithdebinfo.cmake
/usr/lib32/cmake/SPIRV-Tools-tools/SPIRV-Tools-toolsTargets.cmake
/usr/lib32/cmake/SPIRV-Tools/SPIRV-ToolsConfig.cmake
/usr/lib32/cmake/SPIRV-Tools/SPIRV-ToolsTarget-relwithdebinfo.cmake
/usr/lib32/cmake/SPIRV-Tools/SPIRV-ToolsTarget.cmake
/usr/lib32/pkgconfig/32SPIRV-Tools-shared.pc
/usr/lib32/pkgconfig/32SPIRV-Tools.pc
/usr/lib32/pkgconfig/SPIRV-Tools-shared.pc
/usr/lib32/pkgconfig/SPIRV-Tools.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libSPIRV-Tools-diff.so
/usr/lib64/libSPIRV-Tools-link.so
/usr/lib64/libSPIRV-Tools-lint.so
/usr/lib64/libSPIRV-Tools-opt.so
/usr/lib64/libSPIRV-Tools-reduce.so
/usr/lib64/libSPIRV-Tools-shared.so
/usr/lib64/libSPIRV-Tools.so

%files lib32
%defattr(-,root,root,-)
/usr/lib32/libSPIRV-Tools-diff.so
/usr/lib32/libSPIRV-Tools-link.so
/usr/lib32/libSPIRV-Tools-lint.so
/usr/lib32/libSPIRV-Tools-opt.so
/usr/lib32/libSPIRV-Tools-reduce.so
/usr/lib32/libSPIRV-Tools-shared.so
/usr/lib32/libSPIRV-Tools.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/SPIRV-Tools/2b8b815229aa8a61e483fb4ba0588b8b6c491890
/usr/share/package-licenses/SPIRV-Tools/9a84200f47e09abfbde1a6b25028460451b23d03
